# Generated by Django 4.2.7 on 2023-12-06 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Academic Status',
            },
        ),
        migrations.CreateModel(
            name='Degrees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Degrees',
            },
        ),
        migrations.CreateModel(
            name='HeardAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heard_about', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Heard About',
            },
        ),
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Scores',
            },
        ),
        migrations.CreateModel(
            name='SemesterOfEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Semester of Entry',
            },
        ),
        migrations.CreateModel(
            name='MAPLForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('middlename', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('byuid', models.CharField(max_length=9)),
                ('phone', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=100)),
                ('gpa', models.CharField(max_length=100)),
                ('location_of_experience', models.TextField()),
                ('location_from_date', models.DateField()),
                ('location_to_date', models.DateField()),
                ('opi_date', models.DateField()),
                ('wpt_date', models.DateField()),
                ('alt_date', models.DateField()),
                ('art_date', models.DateField()),
                ('other_test_name', models.CharField(max_length=100)),
                ('other_test_score', models.CharField(max_length=100)),
                ('other_test_date', models.DateField()),
                ('institution_name', models.CharField(max_length=100)),
                ('institution_location', models.CharField(max_length=100)),
                ('institution_from_date', models.DateField()),
                ('institution_to_date', models.DateField()),
                ('graduation_date', models.DateField()),
                ('recommender_name_1', models.CharField(max_length=100)),
                ('recommender_title_1', models.CharField(max_length=100)),
                ('recommender_institution_1', models.CharField(max_length=100)),
                ('recommender_email_1', models.EmailField(max_length=100)),
                ('recommender_phone_1', models.CharField(max_length=100)),
                ('recommender_name_2', models.CharField(max_length=100)),
                ('recommender_title_2', models.CharField(max_length=100)),
                ('recommender_institution_2', models.CharField(max_length=100)),
                ('recommender_email_2', models.EmailField(max_length=100)),
                ('recommender_phone_2', models.CharField(max_length=100)),
                ('statement_of_purpose', models.FileField(upload_to='')),
                ('student_signature', models.CharField(max_length=100)),
                ('student_date', models.DateField()),
                ('academic_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapl.academicstatus')),
                ('alt_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapl_alt_scores', to='mapl.scores')),
                ('art_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapl_art_scores', to='mapl.scores')),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapl.degrees')),
                ('heard_about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapl.heardabout')),
                ('opi_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapl_opi_scores', to='mapl.scores')),
                ('semester_of_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapl.semesterofentry')),
                ('wpt_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapl_wpt_scores', to='mapl.scores')),
            ],
        ),
    ]
