# Generated by Django 4.2.6 on 2023-10-05 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OPIForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agree', models.BooleanField()),
                ('entry_date', models.DateField(auto_now_add=True)),
                ('entry_time', models.TimeField(auto_now_add=True)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('byuid', models.CharField(max_length=9)),
                ('netid', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('reason', models.CharField(max_length=100)),
                ('reason_other', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('language_other', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=100)),
                ('second_major', models.CharField(max_length=100)),
                ('minor', models.CharField(max_length=100)),
                ('scores', models.CharField(max_length=100)),
                ('come_to_campus', models.CharField(max_length=100)),
                ('cannot_come', models.CharField(max_length=100)),
                ('testdate1', models.DateField(max_length=100)),
                ('time1', models.TimeField()),
                ('time2', models.TimeField()),
                ('testdate2', models.DateField(max_length=100)),
                ('time3', models.TimeField()),
                ('time4', models.TimeField()),
                ('CertificateStatus', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
            ],
        ),
    ]
