# Generated by Django 4.2.7 on 2024-06-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_students_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='LASER_Queries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_label', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('query', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Laser Queries',
                'verbose_name_plural': 'Laser Queries',
            },
        ),
    ]
