# Generated by Django 4.2.7 on 2024-07-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_laser_queries'),
    ]

    operations = [
        migrations.CreateModel(
            name='OPIc_Diagnostic_Grid_Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'OPIc Diagnostic Grid Languages',
                'verbose_name_plural': 'OPIc Diagnostic Grid Languages',
            },
        ),
    ]
