# Generated by Django 4.0.4 on 2022-09-06 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opiform',
            name='testdate1',
            field=models.DateField(max_length=100),
        ),
    ]
