# Generated by Django 4.1.1 on 2022-10-31 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_opiform_testdate1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opiform',
            name='graduate',
        ),
    ]
