# Generated by Django 4.1.1 on 2022-12-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_opiform_graduate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opiform',
            old_name='agree',
            new_name='Agree',
        ),
        migrations.AlterField(
            model_name='opiform',
            name='firstname',
            field=models.CharField(help_text='This is your first name', max_length=100),
        ),
    ]
