# Generated by Django 4.1.4 on 2022-12-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_agree_opiform_agree_alter_opiform_firstname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opiform',
            old_name='Agree',
            new_name='agree',
        ),
        migrations.AlterField(
            model_name='opiform',
            name='firstname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='opiform',
            name='language',
            field=models.CharField(choices=[('', ''), ('ARAB', 'Arabic'), ('Cebuano', 'Cebuano'), ('DUTCH', 'Dutch'), ('ENGL', 'English'), ('FINN', 'Finnish'), ('FREN', 'French'), ('CHIN', 'Mandarin'), ('GERM', 'German'), ('INDON', 'Indonesian'), ('ITAL', 'Italian'), ('JAPAN', 'Japanese'), ('KOREA', 'Korean'), ('NORWE', 'Norwegian'), ('PORT', 'Portuguese'), ('RUSS', 'Russian'), ('SPAN', 'Spanish'), ('TAGAL', 'Tagalog'), ('THAI', 'Thai'), ('VIET', 'Vietnamese'), ('CREOL', 'Haitian Creole'), ('Other', 'Other')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='opiform',
            name='reason',
            field=models.CharField(choices=[('', ''), ('ASIAN 495', 'ASIAN 495'), ('ARAB 495', 'ARAB 495'), ('CHIN 495', 'CHIN 495'), ('CLS Instructor', 'CLS Instructor'), ('FLAS Pre-test', 'FLAS Pre-test'), ('FLAS Post-test', 'FLAS Post-test'), ('FLANG 300', 'FLANG 300'), ('FREN 491', 'FREN 491'), ('FREN 495', 'FREN 495'), ('GERM 400', 'GERM 400'), ('Individual Request', 'Individual Request'), ('ITAL 491', 'ITAL 491'), ('JAPAN 495', 'JAPAN 495'), ('KOREA 491', 'KOREA 491'), ('Lanuage Certificate', 'Lanuage Certificate'), ('LaSER', 'LaSER'), ('LT AM 495', 'LT AM 495'), ('MAPL', 'MAPL'), ('Research', 'Research'), ('Program Applicant', 'Program Applicant'), ('SLaT Program', 'SLaT Program'), ('LSR Pre', 'LSR Pre'), ('LSR Post', 'LSR Post'), ('PORT 491', 'PORT 491'), ('PORT 493', 'PORT 493'), ('RUSS 492', 'RUSS 492'), ('SPAN 491', 'SPAN 491'), ('SPAN 493', 'SPAN 493'), ('Study Abroad Pre-test', 'Study Abroad Pre-test'), ('Study Abroad Post-test', 'Study Abroad Post-test')], default='', max_length=100),
        ),
    ]
