# Generated by Django 4.2.7 on 2024-02-02 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_agree_opiform_agree_alter_opiform_firstname'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComeToCampusReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campusreason', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Campus Reasons',
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('byu_course_key', models.CharField(help_text='Enter the BYU course key for this course. Example: RUSS 321, SPAN 323R', max_length=100)),
                ('language', models.CharField(help_text='Enter what language this course is for. Example: Russian, Spanish', max_length=100)),
                ('language_abbreviation', models.CharField(help_text='Enter the abbreviation for the language. Example: RUSS, SPAN', max_length=100)),
                ('type_language', models.BooleanField(default=False, help_text='Check this box if this course is a language course')),
                ('type_civilization_culture', models.BooleanField(default=False, help_text='Check this box if this course is a civilization/culture course')),
                ('type_literature', models.BooleanField(default=False, help_text='Check this box if this course is a literature course')),
            ],
            options={
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='LanguageExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_language', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='Reasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=100)),
                ('seminar', models.BooleanField(default=False, help_text='Check this box if reason is a seminar course')),
                ('notification', models.BooleanField(default=False, help_text='Check this box if you want to be notified when someone submits this reason upon submission')),
                ('approve', models.BooleanField(default=False, help_text='Auto Approval: Check this box if you want to automatically approve this reason upon submission')),
            ],
            options={
                'verbose_name_plural': 'Reasons',
            },
        ),
        migrations.RenameField(
            model_name='opiform',
            old_name='confirm_email',
            new_name='CertificateStatus',
        ),
        migrations.RenameField(
            model_name='opiform',
            old_name='Agree',
            new_name='agree',
        ),
        migrations.AlterField(
            model_name='opiform',
            name='come_to_campus',
            field=models.CharField(choices=[('', ''), ('Yes', 'Yes'), ('No', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='opiform',
            name='firstname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='opiform',
            name='scores',
            field=models.CharField(choices=[('', ''), ('Yes', 'Yes'), ('No', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='opiform',
            name='cannot_come',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.cometocampusreason'),
        ),
        migrations.AlterField(
            model_name='opiform',
            name='experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.languageexperience'),
        ),
        migrations.AlterField(
            model_name='opiform',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.languages'),
        ),
        migrations.AlterField(
            model_name='opiform',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.reasons'),
        ),
    ]
