# Generated by Django 4.1.4 on 2023-03-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_agree_opiform_agree_alter_opiform_firstname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableLanguages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_language', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SLATForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('byuid', models.CharField(max_length=9)),
                ('language', models.CharField(choices=[('', ''), ('French', 'French'), ('Mandarin', 'Mandarin'), ('German', 'German'), ('Russian', 'Russian'), ('Spanish', 'Spanish'), ('Portuguese', 'Portuguese')], default='', max_length=100)),
                ('thesis', models.DateField()),
                ('transcript', models.FileField(upload_to='')),
                ('opi', models.FileField(upload_to='')),
                ('letter', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='opiform',
            name='cannot_come',
            field=models.CharField(choices=[('', ''), ('NA', 'NA'), ('Quarantine/Medical Reason', 'Quarantine/Medical Reason'), ('Located outside of Utah County', 'Located outside of Utah County')], max_length=100),
        ),
        migrations.AlterField(
            model_name='opiform',
            name='come_to_campus',
            field=models.CharField(choices=[('', ''), ('Yes', 'Yes'), ('No', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='opiform',
            name='experience',
            field=models.CharField(choices=[('', ''), ('Mission', 'Mission'), ('Native speaker', 'Native speaker'), ('Heritage speaker (you learned it at home, through family members', 'Heritage speaker (you learned it at home, through family members'), ('Beginner', 'Beginner'), ('Professional', 'Professional'), ('University Taught', 'Learned through University/High School Courses')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='opiform',
            name='language',
            field=models.CharField(choices=[('', ''), ('ARAB', 'Arabic'), ('CEBU', 'Cebuano'), ('DANSH', 'Danish'), ('DUTCH', 'Dutch'), ('ENGL', 'English'), ('FINN', 'Finnish'), ('FREN', 'French'), ('CHIN', 'Mandarin'), ('GERM', 'German'), ('INDON', 'Indonesian'), ('ITAL', 'Italian'), ('JAPAN', 'Japanese'), ('KOREA', 'Korean'), ('NORWE', 'Norwegian'), ('PORT', 'Portuguese'), ('RUSS', 'Russian'), ('SPAN', 'Spanish'), ('TAGAL', 'Tagalog'), ('THAI', 'Thai'), ('VIET', 'Vietnamese'), ('CREOL', 'Haitian Creole'), ('Other', 'Other')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='opiform',
            name='reason',
            field=models.CharField(choices=[('', ''), ('ASIAN 495', 'ASIAN 495'), ('ARAB 495', 'ARAB 495'), ('CHIN 495', 'CHIN 495'), ('FLANG 300', 'FLANG 300'), ('FREN 491', 'FREN 491'), ('FREN 495', 'FREN 495'), ('GERM 400', 'GERM 400'), ('ITAL 491', 'ITAL 491'), ('JAPAN 495', 'JAPAN 495'), ('KOREA 491', 'KOREA 491'), ('LT AM 495', 'LT AM 495'), ('PORT 491', 'PORT 491'), ('PORT 493', 'PORT 493'), ('RUSS 492', 'RUSS 492'), ('SPAN 491', 'SPAN 491'), ('SPAN 493', 'SPAN 493'), ('Language Certificate', 'Language Certificate'), ('LaSER', 'LaSER'), ('SLaT Program', 'SLaT Program'), ('CLS Instructor', 'CLS Instructor'), ('FLAS Pre-test', 'FLAS Pre-test'), ('FLAS Post-test', 'FLAS Post-test'), ('MAPL', 'MAPL'), ('Research', 'Research'), ('Program Applicant', 'Program Applicant'), ('LSR Pre', 'LSR Pre'), ('LSR Post', 'LSR Post'), ('Study Abroad Pre-test', 'Study Abroad Pre-test'), ('Study Abroad Post-test', 'Study Abroad Post-test'), ('Individual Request', 'Individual Request')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='opiform',
            name='scores',
            field=models.CharField(choices=[('', ''), ('Yes', 'Yes'), ('No', 'No')], max_length=10),
        ),
    ]
