# Generated by Django 4.2.7 on 2024-02-02 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_cometocampusreason_courses_languageexperience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reasons',
            name='approve',
            field=models.BooleanField(help_text='Auto Approval: Check this box if you want to automatically approve this reason upon submission'),
        ),
    ]
