# Generated by Django 4.2.7 on 2024-02-02 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_reasons_approve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reasons',
            name='approve',
            field=models.BooleanField(default=False, help_text='Auto Approval: Check this box if you want to automatically approve this reason upon submission'),
        ),
    ]
