# Generated by Django 4.1.4 on 2023-03-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_availablelanguages_reasons_slatform_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_language', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.DeleteModel(
            name='AvailableLanguages',
        ),
        migrations.AlterModelOptions(
            name='reasons',
            options={'verbose_name_plural': 'Reasons'},
        ),
        migrations.RemoveField(
            model_name='slatform',
            name='letter',
        ),
    ]
