# Generated by Django 4.1.4 on 2023-03-28 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_languages_delete_availablelanguages_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Languages',
            new_name='test',
        ),
    ]
