# Generated by Django 4.2.7 on 2024-02-07 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_reasons_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='reasons',
            name='notification_message',
            field=models.TextField(default='A student has sent in an OPI request that requires your attention.', help_text='Enter the message you want to send to the person who submits this reason'),
        ),
    ]
