# Generated by Django 4.2.7 on 2024-02-07 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_reasons_notification_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reasons',
            name='notification_message',
            field=models.TextField(default='A student has sent in an OPI request that requires your attention.', help_text='Enter the message you want to send to the person who submits this reason. This automatically includes the reason and student record ID at the end of the message.'),
        ),
    ]
