# Generated by Django 4.1.4 on 2023-03-28 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_languages_test'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='test',
            new_name='Languages',
        ),
    ]
