# Generated by Django 4.2.2 on 2023-06-24 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_test_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opiform',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.languages'),
        ),
        migrations.AlterField(
            model_name='opiform',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.reasons'),
        ),
    ]
