# Generated by Django 4.2.2 on 2023-06-24 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_opiform_language_alter_opiform_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComeToCampusReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campusreason', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Campus Reasons',
            },
        ),
        migrations.CreateModel(
            name='LanguageExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='opiform',
            name='cannot_come',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.cometocampusreason'),
        ),
        migrations.AlterField(
            model_name='opiform',
            name='experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.languageexperience'),
        ),
    ]
