# Generated by Django 4.2.7 on 2024-02-16 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_cometocampusreason_campusreason'),
    ]

    operations = [
        migrations.AddField(
            model_name='reasons',
            name='reject',
            field=models.BooleanField(default=False, help_text='Auto Reject: Check this box if you want to automatically reject this reason upon submission. Students will not have to be approved by you to have their test scheduled. This is not recommended for most reasons.'),
        ),
    ]
