# Generated by Django 4.2.2 on 2023-08-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_academicstatus_heardabout_scores_semesterofentry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maplform',
            name='statement_of_purpose',
            field=models.FileField(upload_to=''),
        ),
    ]
