# Generated by Django 4.2.2 on 2023-08-03 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_maplform_statement_of_purpose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maplform',
            name='heard_about_other',
        ),
    ]
