# Generated by Django 4.2.2 on 2023-08-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_maplform_heard_about_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maplform',
            name='location_of_experience',
            field=models.TextField(),
        ),
    ]
