# Generated by Django 4.2.2 on 2023-08-03 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_maplform_location_of_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degrees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heard_about', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Degrees',
            },
        ),
        migrations.AlterField(
            model_name='maplform',
            name='degree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.degrees'),
        ),
    ]
