# Generated by Django 4.2.2 on 2023-08-03 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_degrees_alter_maplform_degree'),
    ]

    operations = [
        migrations.RenameField(
            model_name='degrees',
            old_name='heard_about',
            new_name='degree',
        ),
    ]
