# Generated by Django 4.2.7 on 2023-12-01 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_rename_heard_about_degrees_degree'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opiform',
            old_name='confirm_email',
            new_name='CertificateStatus',
        ),
    ]
