# Generated by Django 4.2.7 on 2023-12-06 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_rename_confirm_email_opiform_certificatestatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maplform',
            name='academic_status',
        ),
        migrations.RemoveField(
            model_name='maplform',
            name='alt_score',
        ),
        migrations.RemoveField(
            model_name='maplform',
            name='art_score',
        ),
        migrations.RemoveField(
            model_name='maplform',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='maplform',
            name='heard_about',
        ),
        migrations.RemoveField(
            model_name='maplform',
            name='opi_score',
        ),
        migrations.RemoveField(
            model_name='maplform',
            name='semester_of_entry',
        ),
        migrations.RemoveField(
            model_name='maplform',
            name='wpt_score',
        ),
        migrations.DeleteModel(
            name='SLATForm',
        ),
        migrations.DeleteModel(
            name='AcademicStatus',
        ),
        migrations.DeleteModel(
            name='Degrees',
        ),
        migrations.DeleteModel(
            name='HeardAbout',
        ),
        migrations.DeleteModel(
            name='MAPLForm',
        ),
        migrations.DeleteModel(
            name='Scores',
        ),
        migrations.DeleteModel(
            name='SemesterOfEntry',
        ),
    ]
