# Generated by Django 4.2.7 on 2023-12-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SLATForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('byuid', models.CharField(max_length=9)),
                ('language', models.CharField(choices=[('', ''), ('French', 'French'), ('Mandarin', 'Mandarin'), ('German', 'German'), ('Russian', 'Russian'), ('Spanish', 'Spanish'), ('Portuguese', 'Portuguese')], default='', max_length=100)),
                ('thesis', models.DateField()),
                ('transcript', models.FileField(upload_to='')),
                ('opi', models.FileField(upload_to='')),
            ],
        ),
    ]
